Traceback (most recent call last):
  File "/home/varunkapoor/anaconda3/envs/naparienv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/varunkapoor/anaconda3/envs/naparienv/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/varunkapoor/anaconda3/envs/naparienv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/varunkapoor/anaconda3/envs/naparienv/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/varunkapoor/anaconda3/envs/naparienv/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/varunkapoor/anaconda3/envs/naparienv/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/varunkapoor/anaconda3/envs/naparienv/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%gui qt5
from napatrackmater.Trackvector import TrackVector
from pathlib import Path
from ipywidgets import interactive, widgets
from IPython.display import display
import napari 
from tifffile import imread
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
from scipy.spatial.distance import pdist
from scipy.cluster.hierarchy import linkage, fcluster
import matplotlib.pyplot as plt
------------------

----- stderr -----
2023-11-18 14:08:24.729227: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
----- stderr -----
2023-11-18 14:08:25.358781: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mgui[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mqt5[39m[38;5;124m'[39m)
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnapatrackmater[39;00m[38;5;21;01m.[39;00m[38;5;21;01mTrackvector[39;00m [38;5;28;01mimport[39;00m TrackVector
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpathlib[39;00m [38;5;28;01mimport[39;00m Path
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipywidgets[39;00m [38;5;28;01mimport[39;00m interactive, widgets

File [0;32m~/anaconda3/envs/naparienv/lib/python3.10/site-packages/napatrackmater/__init__.py:2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mpretrained[39;00m [38;5;28;01mimport[39;00m register_model, register_aliases, clear_models_and_aliases
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mclustering[39;00m [38;5;28;01mimport[39;00m Clustering
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mDeepEmbeddedClustering[39;00m [38;5;28;01mimport[39;00m DeepEmbeddedClustering
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mCloudAutoEncoder[39;00m [38;5;28;01mimport[39;00m CloudAutoEncoder

File [0;32m~/anaconda3/envs/naparienv/lib/python3.10/site-packages/napatrackmater/clustering.py:1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mkapoorlabs_lightning[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlightning_trainer[39;00m [38;5;28;01mimport[39;00m AutoLightningModel
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcellshape_helper[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvendor[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpytorch_geometric_files[39;00m [38;5;28;01mimport[39;00m read_off, sample_points
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m

[0;31mModuleNotFoundError[0m: No module named 'kapoorlabs_lightning'

